const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    apis: ['src/routes.js'],
    basePath: '/',
    swaggerDefinition: {
      info: {
        description: 'Test API with autogenerated swagger doc',
        swagger: '2.0',
        title: 'Ticketor API',
        version: '2.0.0',
      },
    },
  };
  const specs = swaggerJsdoc(options);
 module.exports = specs;